modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/CCr4ft3r/geotagged-screenshots/issues"
[[mods]]
modId="${mod_id}"
version="${minecraft_version}-${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${mod_authors}"
displayTest="MATCH_VERSION"
side = "BOTH"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="xaeroworldmap"
   mandatory=true
   versionRange="[1.30.6,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.${mod_id}]]
   modId="xaerominimap"
   mandatory=true
   versionRange="[23.5.0,)"
   ordering="NONE"
   side="CLIENT"